### ISSUE TITLE
Roadmap for experimental release

### ISSUE THREAD

**Issue by angusmcb** [angusmcb/wntr-qgis#1]
To do for experimental release:

- [x] Expand readme.md to cover simple use case
- [x] Tests working for round-trip in various file formats
- [x] Test to check results for a simple network match after going through qgis or direct from.inp
- [x] Consisent, basic styles for each input/output layer
- [x] Reasonable descriptions of each of processing algorithms
- [x] Code style checks passing
- [x] Set up necessary metadata for QGIS plugin repository

Not for experimental release:
- Controls
- Exposing all possible options
- List of demand patterns for junctions
- Website
- Extremely complicated test case
- Tests on warnings

**Comment by angusmcb** [comment]
Also need to manage unit converesion, but not for experimental release.

**Comment by angusmcb** [comment]
Experimental plugin released to qgis plugin repository :-)
