### ISSUE TITLE
todo towards stable release 

### ISSUE THREAD

**Issue by angusmcb** [angusmcb/wntr-qgis#4]
- [ ]  documentation site
- [ ] toolbar buttons fully functional
- [ ] settings dialog for run button
- [ ] simple example
- [ ] complex example with every element type
- [ ] examples load without any message about transform
- [ ] results layer styling adapting to results
- [ ] pretty results output
- [ ] every possible element type and option added
- [ ] remove wheels
- [ ] API tests
